# fly.toml app configuration file generated for mlb-mcp on 2025-06-10T18:18:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mlb-mcp'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
